### PR TITLE
Fix handling of small timesteps

### PR DESCRIPTION
**Pull request by sjdaines**
Sundials solver is allowed to warn and continue if it returns a timestep with no change in t.
If the solver doesn't recover, it will fail with eg `SciMLBase.ReturnCode.MaxIters`

Reverts PR https://github.com/SciML/Sundials.jl/pull/416, fixes https://github.com/SciML/Sundials.jl/issues/420

For CVode and ARKode, it looks like this is intended behaviour: the Sundial solver emits a warning message, with an API call

    CVodeSetMaxHnilWarns
    ARKStepSetMaxHnilWarns
to set the maximum number of warning messages printed, which is exposed to Julia as

    max_hnil_warns
see Sundials driver code https://github.com/LLNL/sundials/blob/e8a3e67e3883bc316c48bc534ee08319a5e8c620/src/cvode/cvode.c#L1339-L1347

For IDA, there is no API like this so it's not so clear what should happen, however the behaviour prior to PR https://github.com/SciML/Sundials.jl/pull/416 (and restored by this PR) for the `f_noconverge` test added in `test/common_interface/ida.jl` is to return `SciMLBase.ReturnCode.MaxIters`
which seems reasonable?

(NB: @oscardssmith I can't reproduce the issue implied by the title of PR https://github.com/SciML/Sundials.jl/pull/416 so perhaps what is missing here is the original failure case? The call to solve in the f_noconverge test [`test/common_interface/ida.jl`](https://github.com/SciML/Sundials.jl/blob/ca8ac7cd0c0c9d096abcbaf904f88b16b9bc6356/test/common_interface/ida.jl#L117-L120), returns `SciMLBase.ReturnCode.MaxIters`, it doesn't return with no error?

Also issue https://github.com/SciML/SciMLBase.jl/issues/458 shows IDA printing

    [IDAS ERROR]  IDASolve
      At t = 0 and h = 1.49012e-18, the error test failed repeatedly or with |h| = hmin.
which suggests that IDA did flag an error in that case ? )

### CODE REVIEW

**Comment by oscardssmith** [comment]
> however the behaviour prior to PR https://github.com/SciML/Sundials.jl/pull/416 (and restored by this PR) for the f_noconverge test added in test/common_interface/ida.jl is to return SciMLBase.ReturnCode.MaxIters
which seems reasonable?

The problem with this is that it does return `MaxIters` but it only does so after spending `MaxIters` iterations which for non-trivial systems will be extremely slow. It looks like the behavior this PR re-enables is the better behavior for the non-IDA solvers. Would you be willing to adjust this PR to make it so it does fail with IDA but not the other solvers?

**Comment by sjdaines** [comment]
OK so it looks like this is really a feature request for an early return from solver failure? So I'd suggest:
1. Log an issue to that effect: 'enhancement request: early return from solver failure' or similar
2. Either revert https://github.com/SciML/Sundials.jl/pull/416 (or apply this PR).  The problem as I see it is that this is really a non-trivial design change (as well as currently a breaking change and a regression in robustness) that interacts with solver robustness and needs some more information and some thought. And currently we're doing this process backwards...

I did a little more digging into Sundials IDA to understand what is needed here:
- The SciML defaults for `maxiters` (= 1e5) are much larger than the Sundials defaults (= 500 for CVode, ARKode and IDA) so that is possibly contributing to the issue seen here (I'm *not* suggesting changing this ! Probably worth a note in the documentation though)
- In Sundials 6.2 there is a new API call `IDASetMinStep` (ie make use of `dtmin` in the SciML interface) which might be the preferred fix, but that isn't available in the current Julia v5.2 jll,  So that I think is an incentive to update ie https://github.com/SciML/Sundials.jl/pull/415
- To understand the behaviour of the 'native' IDA main loop (`IDASolve` with option `IDA_NORMAL` to timestep until a supplied `tout`, cf Julia executes single steps using `IDA_ONE_STEP`) I wrote a C test case that uses `f_noconverge` from `test/common_interface/ida.jl`.  Testing with Sundial 6.2.1 this shows that `IDAsolve()` errors with flag -1 and message `At t = 1,  mxstep steps taken before reaching tout`.  So the the native IDA main loop doesn't appear to implement any special-casing for timestep going to zero, which suggests this is an intentional design decision.

So if we do want to implement an early return from failure, it looks to me like either a) this would need to be clearly identified as an additional feature added by SciML (ie a behaviour change, not just an interface to Sundials), and that it would need to do something like count the number of consecutive zero-length steps and error if some configurable threshold is exceeded; or b) we need more information about the IDA design.

**Comment by oscardssmith** [comment]
thanks for digging in to this. I think the main tension here is whether we want the sundials wrapper to be a light wrapper over the c++ code or a set of solvers that integrate as well as possible into the SciML stack. The rest of our summers specify a dtmin which is usually based on making sure we don't take size zero steps. this not only prevents infinite loops, but also makes things like when callbacks trigger unambiguous. I think the thing I would need to see before I was comfortable merging this was an example where a solver actually completes after taking a zero length step.

**Comment by sjdaines** [comment]
[This](https://github.com/PALEOtoolkit/PALEOcopse.jl/actions/runs/6283272790/job/17063573301#step:6:2523) CI log is an example of CVODE failure and then recovery (the original CI failure from https://github.com/SciML/Sundials.jl/issues/420 without the change from PR https://github.com/SciML/Sundials.jl/pull/416)

Here CVODE recovers and the solution uses 3527 function evaluations for 2278 timesteps.

I just tried the same test case using some other solvers (this is a small stiff system of 19 equations), all at reltol=1e-4:
- Sundials IDA 3986 evals, 2315 steps (no warnings logged)
- LSODA.lsoda()   evals not reported, 9155 steps  (no warnings logged)
- (also from memory a MATLAB version of this code gave similar results to CVODE using the ode15s solver)

and the recommended SciML native solvers for stiff systems:
- OrdinaryDiffEq.Rosenbrock23(autodiff=false) 131039 evals, 5429 steps (so ~30x the function evals and ~20x slower than CVODE)
- OrdinaryDiffEq.TRBDF2(autodiff=false) 129302 evals, 23478 steps
- OrdinaryDiffEq.FBDF(autodiff=false)) fails with `retcode=DtLessThanMin`
- OrdinaryDiffEq.QNDF(autodiff=false)) fails with `retcode=DtLessThanMin`

So in this case, consistency with the SciML solvers is definitely *not* what we want !!

I'm sure there is something that could be changed (eg scaling of variables, etc) to make this problem more solver-friendly, but looking at this from the point of view of solver robustness, this is consistent with my subjective impression that the Sundials CVODE and IDA solvers are a great deal more robust than the SciML solvers on "real world" problems.  I suspect this takes years of incremental improvements as a result of user feedback to achieve, and isn't fully captured by small test cases.

From my point of view as a user, I personally would prefer a SciML design that maintains the strengths and full performance and robustness of the native and wrapped solvers, even if this means that additional user configuration is required where the pieces don't exactly fit. Otherwise the risk is that this results in a lowest-common-denominator.

For the specific design question here about handling of small timesteps, if it is a design decision of SciML to require that `solver_step` always returns a timestep > 0, then perhaps that could be handled by additional code within the Sundials-specific `solver_step` that makes multiple calls to `CVode()` etc (up to some configurable limit < maxsteps if you want to also provide an early error return) ?  But this is already adding complexity of course and possibly reducing robustness or making issues harder to debug, so it's not obvious to me that this is a good idea...

**Comment by oscardssmith** [comment]
Fair enough. I think I am now in favor of this PR.

@ChrisRackauckas do you have thoughts on what we should do here on the OrdinaryDiffEq side? Should the Julia stiff solvers use extended precision tracking of time?

**Comment by ChrisRackauckas** [comment]
> So in this case, consistency with the SciML solvers is definitely not what we want !!

I mean, I could also make dumb comparisons which only include 2nd order methods with Sundials, restricting its order arbitrarily to make it slower. Obviously showing Rosenbrock23 and TRBDF2 in this kind of case is a straw man. Did you try the recommended list?

> this is consistent with my subjective impression that the Sundials CVODE and IDA solvers are a great deal more robust than the SciML solvers on "real world" problems

I wouldn't make such a statement from a very small set of academic cases. We have seen more often than not CVODE and IDA fail pretty spectacularly on many problems. Many of the benchmarks have had to had tolerances adjusted just to accommodate the run failures of Sundials. The one thing CVODE/IDA seems to work on are reaction-advection-diffusion types of problems, anything with dominant complex eigenvalues is rather suspect. When you have one use case that work with a given solver, sure that one tends to look good, but other the wide use cases that we have explored and benchmarked, industry and academic, this seems to be far from the truth. If you think otherwise, please start sharing benchmarks to the SciMLBenchmarks that we can explore more deeply. Currently there, Sundials tends to fail in a lot of cases with higher tolerances and many cases had tolerances adjusted just so that Sundials would not diverge. If you only benchmark the problems of one domain you will not see the full set of behaviors.

Note that one major complaint with the Sundials solvers is that on average they have a tendency to solve equations with a lot more error than the requested tolerance, a lot more than other solvers by an order of magnitude or two, which tends to make it look a bit better in "eye tests" simply because the solver gives a "good enough" trajectory fast that is very inaccurate. You can see that as the right shift in the benchmarks. To account for this you really need to compute reference trajectories and clearly calculate the solution error. Solvers at the same tolerances are not solving to the same accuracy, and CVODE is very clearly the one that relaxes the accuracy of the solvers the most in almost every benchmark we've seen. On average, asking for 6 digits of accuracy gives only 3 with Sundials, while closer to 5 with a Rosenbrock method for example. If your eyeball test only cares about a few digits of accuracy, that's fine, but we really need to care that equations are solved not just fast but also correctly.

> I personally would prefer a SciML design that maintains the strengths and full performance and robustness of the native and wrapped solvers, even if this means that additional user configuration is required where the pieces don't exactly fit. Otherwise the risk is that this results in a lowest-common-denominator.

I mean, that's kind of an odd way to determine "lowest-common-denominator". Options which give the direct possibility of silently incorrect and non-convergent behavior should not be taken lightly. I am also of the opinion that we should lighten the checks on minimum dt throwing, but do understand that the reason that is there stems from the justification of the Hairer Fortran codes that such a behavior can lead to incorrect solutions in some cases. The Sundials implementation seems to just not worry about warning/erroring in those cases and continue forward, and by doing so in many cases it will give a correct answer, though in some cases it can lose convergence guarantees and simply give a wrong answer. Such a behavior isn't obviously the best idea right out of the gate and shouldn't just be taken lightly: solving equations fast is different from solving them accurately, and accurately seems to be what Sundials has a lot of trouble with.

That said as stated above, I do think the Hairer approach is a bit too heavy handed since solvers do have a recovery behavior more often than not. The default error checking should probably be much more direct to the exact behavior to stop infinite looping. The reason for this difference is mostly because the instability of BDF methods tend to make them have dt go very close to zero even when that's not required, simply because the method is unstable (only A-alpha stable, so dominant complex eigenvalues for example can lead to instability and dt->0 type of behavior), while this is not the case for stiffly-stable methods like Rodas5P which have A-B-L stability and thus should in general never have a small dt except when needed for very low tolerance convergence. Since the Hairer suite is all (I)RK methods and Rosenbrock methods with sufficient stability criteria, this diagnostic thus barely ever gets in the way, which is why you see Rosenbrock23 and TRBDF2, while bad choices for this case, will simply chug along and solve it. The issue though is that somewhere along the line we added A-alpha stable methods, which need small dt handling to recover around things like area of high complex eignevalues or events, but the error checking behavior was kept stricter in the form of assuming L-stability. In most cases it does not hurt to relax this, and so the best thing to do here is probably to just relax it so that BDF methods have an easier time recovering. We could make this be something that is solver-dependent, but keeping the rules simpler might be good.

In that case we could do the following. Inside of the solver loop, it should check whether `t + dt == t` and error out by default if that is the case. It can just use `DtLessThanMin`. We can have a default `dtmin=nothing` which then only is checking for `dt>eps(t)` at each step, which is equivalent to what Sundials does by default.

>  if it is a design decision of SciML to require that solver_step always returns a timestep > 0, then perhaps that could be handled by additional code within the Sundials-specific solver_step that makes multiple calls to CVode() etc (up to some configurable limit < maxsteps if you want to also provide an early error return) ? But this is already adding complexity of course and possibly reducing robustness or making issues harder to debug, so it's not obvious to me that this is a good idea...

Sundials also only allows a timestep > 0. It's not numerically robust to allow time steps < 0 because reverse solves are not in general numerically stable, and in fact there are many cases where a reverse solve is unconditionally unstable for any `|dt|>0` (for example, upwinding schemes for advection). So if you let dt<0 as a way to reverse, you do not generally get to the same point and you will introduce numerical error in many cases which does not have a reverse stability property. Sundials' default minimum step is zero and so it effectively defaults to a minimum dt of `dt>eps(t)`. Thus the scheme above would give it similar behavior in OrdinaryDiffEq. 

We should give this a try and see if it's all that's required for a BDF to handle this case effectively. Did you try just setting `dtmin=0`?

**Comment by ChrisRackauckas** [comment]
Did you spawn the dtmin=0 run?

**Comment by ChrisRackauckas** [comment]
Do you have the MWE you can share? Can even have the packages. I just want to do some proper testing on this and don't have a case.

**Comment by ChrisRackauckas** [comment]
@sjdaines I would still like to dig into those results you have on your CI there. I played with this a lot in other examples and led to the conclusion that we should not just change dtmin=0 here but also generally in DifferentialEquations.jl. Full justification in https://github.com/SciML/OrdinaryDiffEq.jl/pull/2098. With this, I can't find a case where CVODE succeeds but FBDF doesn't, so it would be good to test more. It turns out this little bit was a major blocker!

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
