### PR TITLE
A clean attempt to try the BB deps for sundials 3

### PR DESCRIPTION
**Pull request by ViralBShah**
Same investigation as #227 but rebased on master.

### CODE REVIEW

**Comment by ViralBShah** [comment]
This still fails in the same way on Windows. Either there is something odd with the wrapping of sundials that is causing a buffer overrun or the windows build is broken. I suspect it is the former.

**Comment by ChrisRackauckas** [comment]
If something was odd with the wrapping of Sundials, why would all of the previous binaries be okay? If that's the line of thought to go down, that would isolate it.

**Comment by ViralBShah** [comment]
It's a valid point, but the only explanation I have is that perhaps different compilers are in use, and that is leading to some issues being exposed that were accidentally working. There is literally no difference in the way we are building sundials now from before. I checked both scripts.

**Comment by ViralBShah** [comment]
Ideally one would be able to load this sort of thing with `valgrind` and see what is going on. Not sure I really want to do that.

**Comment by ViralBShah** [comment]
Basically I am getting pointer values for `SunMatrix` objects that are like `0x0000000004` or `0x0000000009`, which suggests that something is corrupting the memory.

**Comment by ViralBShah** [comment]
@staticfloat @giordano Would you guys know if BB somehow is not building the windows binaries right? The earlier SundialsBuilder was producing working binaries.

Everything is good except for a couple of tests on Windows.

**Comment by giordano** [comment]
I'm not aware of any known problem with Windows builds :confused:   This is still Sundials 3, right?

> The earlier SundialsBuilder was producing working binaries.

There have been too many changes since the old version of BinaryBuilder, hard to tell what may be the difference.

**Comment by ViralBShah** [comment]
Right This is Sundials 3 which worked before when compiled with SundialsBuilder and does not now when built with BB. Only on windows 64 bit.

**Comment by ViralBShah** [comment]
#235 is very close. So we can ignore Sundials 3.

**Pull request closed without merging**
