### PR TITLE
Convert array to realtype

### PR DESCRIPTION
**Pull request by pepijndevos**
NVector only supports realtype values it seems so calling this with an array of any other number type would fail.

### CODE REVIEW

**Comment by pepijndevos** [comment]
I mean the most reduced case is just `convert(Sundials.NVector, [true, false, true])`

And why that happens is DAECompiler uses `Vector{Bool}` for its `differential_vars` which gets passed to IDA during initialisation. Why that doesn't happen for other types of system I'm not sure. Is `differential_vars` normally an array of floats?

https://github.com/SciML/Sundials.jl/blob/dbd89b37e488d98d9c5d4d2355f5770835d95d1f/src/common_interface/integrator_utils.jl#L205

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/Sundials.jl/blob/b88762bdaf4141d1c4363cff8f6175cfca937f39/test/common_interface/jacobians.jl#L80-L85

It has always been booleans. Show me a single example that uses a float? 

https://docs.sciml.ai/DiffEqDocs/stable/tutorials/dae_example/#Implicitly-Defined-Differential-Algebraic-Equations-(DAEs)

Please share one example that fails.

**Comment by ChrisRackauckas** [comment]
> I mean the most reduced case is just convert(Sundials.NVector, [true, false, true])

What causes that to happen in practice and why doesn't it happen with normal DAEProblem usage?

**Comment by pepijndevos** [comment]
I have no idea. I put some debug prints in `function DiffEqBase.initialize_dae!(integrator::IDAIntegrator)` and it doesn't even get hit in your examples. In what cases is that supposed to be called? Because evidently your examples just don't hit this code path but I'm not sure what kind of example will.

**Comment by ChrisRackauckas** [comment]
Try changing the initial condition to be further from a consistent initial condition

**Comment by pepijndevos** [comment]
This should reproduce it, same MWE as https://github.com/SciML/OrdinaryDiffEq.jl/issues/1887 but with IDA, since it appears that the only place where this function gets called in Sundial is in callback stuff.

It also uses a BitVector which seemed to be the thing that actually broke it.

```julia
using OrdinaryDiffEq, Test, Sundials

f = function (out, du, u, p, t)
    out[1] = -p[1] * u[1] + p[3] * u[2] * u[3] - du[1]
    out[2] = +p[1] * u[1] - p[2] * u[2]^2 - p[3] * u[2] * u[3] - du[2]
    out[3] = u[1] + u[2] + u[3] - p[4]
end
u₀ = [1.0, 0, 0]
du₀ = [0.0, 0.0, 0.0]
p = [0.04, 3.0e7, 1.0e4, 1.0]
tspan = (0.0, 100.0)
differential_vars = BitVector([true, true, false])
prob = DAEProblem(f, du₀, u₀, tspan, p, differential_vars = differential_vars)
condition(u, t, integrator) = t-round(t)
affect!(integrator) = integrator.p[4] = 2.0
cb = ContinuousCallback(condition, affect!)

p = [0.04, 3.0e7, 1.0e4, 1.0]
prob = DAEProblem(f, du₀, u₀, tspan, p, differential_vars = differential_vars)
sol = solve(prob, IDA(), callback = cb, tstops = [50.0], abstol = 1e-12, reltol = 1e-12)

```

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
