### PR TITLE
Fix ARKODE reinit

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Needs a test case

### CODE REVIEW

**Comment by superckl** [comment]
I can verify this fixes the error, but callbacks with `ARKODE` still seem to be behaving weird. Take this test case (which resulted in a runtime error previously):
```julia
using Sundials, DiffEqBase, Test

tspan = [0, 200]
E = 1E-2
h0 = 1

fun = ODEFunction((dh, _, _, _) -> dh .= -E, jac = (J, _, _, _) -> J .= 0)
prob = ODEProblem(fun, [h0], tspan)

cb = ContinuousCallback((h, _, _) -> h[1], terminate!)

sol_ark = solve(prob, ARKODE(), callback = cb)
sol_bdf = solve(prob, CVODE_BDF(), callback = cb)

@test isapprox(sol_bdf.t[end], 1/E, rtol = 1E-3)
@test isapprox(sol_bdf[end][1], 0, atol = 1E-3)
@test isapprox(sol_ark.t[end], 1/E, rtol = 1E-3)
@test isapprox(sol_ark[end][1], 0, atol = 1E-3)
```
which outputs
```julia
Test Failed at i:\My Drive\Research\Code\julia solver\Sundials\test\arkode_callback.jl:17
  Expression: isapprox(sol_ark.t[end], 1 / E, rtol = 0.001)
   Evaluated: isapprox(0.0, 100.0; rtol = 0.001)
ERROR: There was an error during testing
```
The system should be integrated to `1/E=1E2` and then stop because `h=0`. With `CVODE_BDF`, all is fine, but `ARKODE` seems to exit at `t=0`. Without the callback, `ARKODE` integrates the system fine:
```julia
display(solve(prob, ARKODE()))
```
```julia
retcode: Success
Interpolation: 3rd order Hermite
t: 6-element Vector{Float64}:
   0.0
   0.004112271831573867
   0.3427118254794238
   5.90547982484689
 117.16083981219622
 200.0
u: 6-element Vector{Vector{Float64}}:
 [1.0]
 [0.9999588772816843]
 [0.9965728817452059]
 [0.9409452017515313]
 [-0.17160839812196294]
 [-1.000000000000002]
```

**Comment by ChrisRackauckas** [comment]
Can you see what happens if you swap fun 1 and 2 in the overload? I think I did it right: we have implicit-explicit and they have explicit-implicit. But double check.

**Comment by ChrisRackauckas** [comment]
Alright, well this is at least right so let's merge this and open an issue to investigate next steps.

**Comment by HumHongeKamyaab** [comment]
Mentioning this discourse thread here https://discourse.julialang.org/t/facing-problems-with-sundials-jl-arkode-with-discrete-callback/119278?u=humhongekamyaab
as it is related with reinit of ARKODE

**Pull request merged**
